# Generated by Django 4.0.6 on 2022-09-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('patientid', models.IntegerField()),
                ('doctorid', models.IntegerField()),
                ('doctorname', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('patientname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('appoinmentdate', models.DateField()),
                ('appoinmenttime', models.TimeField()),
                ('symptoms', models.CharField(max_length=200)),
            ],
        ),
    ]
